# -*- coding: utf-8 -*-
"""ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UGGysD5MtW11bdm0aV8zZAK8wt5lMaDU
"""

import nltk
from nltk.chat.util import Chat, reflections

pairs = [
    [
        r"my name is (.*)",
        ["Hello %1, How are you today?",]
    ],
    [
        r"hi|hey|hello",
        ["Hello", "Hey there",]
    ],
    [
        r"h",
        ["Hello", "Hey there",]
    ],
    [
        r"what is your name?",
        ["I am a bot created by NLTK.",]
    ],
    [
        r"how are you? | How are you",
        ["I'm doing good. How about You?",]
    ],
    [
        r"sorry (.*)",
        ["It's alright.", "No problem.",]
    ],
    [
        r"I am (.*) (good|well|okay|ok)",
        ["Nice to hear that.", "Alright, great!",]
    ],
    [
        r"quit",
        ["Bye-bye, take care. See you soon :) ","It was nice talking to you. See you soon :)"]
    ],
]

def nltk_chatbot():
    print("Hi! I am a simple chatbot created using NLTK. Type 'quit' to exit.")
    chatbot = Chat(pairs, reflections)
    chatbot.converse()

# Start the chatbot
nltk_chatbot()