# -*- coding: utf-8 -*-
"""ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UGGysD5MtW11bdm0aV8zZAK8wt5lMaDU
"""

import nltk
from nltk.chat.util import Chat, reflections

pairs = [
    [
        r"my name is (.*)",
        ["Hello %1, How are you today?",]
    ],
    [
        r"hi|hey|hello",
        ["Hello", "Hey there",]
    ],
    [
        r"h",
        ["Hello", "Hey there",]
    ],
    [
        r"what is your name?",
        ["I am a bot created by NLTK.",]
    ],
    [
        r"how are you? | How are you",
        ["I'm doing good. How about You?",]
    ],
    [
        r"sorry (.*)",
        ["It's alright.", "No problem.",]
    ],
    [
        r"I am (.*) (good|well|okay|ok)",
        ["Nice to hear that.", "Alright, great!",]
    ],
    [
        r"quit",
        ["Bye-bye, take care. See you soon :) ","It was nice talking to you. See you soon :)"]
    ],
]

def nltk_chatbot():
    print("Hi! I am a simple chatbot created using NLTK. Type 'quit' to exit.")
    chatbot = Chat(pairs, reflections)
    chatbot.converse()

# Start the chatbot
nltk_chatbot()




1) ChatBot

i)

import re
responses= {
    "hello":"Hello! How can I assist you today?",
    "price": "Can you please specify whch product or servce you are asking for?",
    "information": "Our company name is ABC enterprices and we are in the business of electronics equipment",
    "name": "Our company is ABC Enterprices PVT LTD",
    "hours": "Our business hours are Monday to Friday, 9AM to 5PM",
    "address":"We are located at 134 Main Street,Springfield",
    "contact": "You can reach us at contact@example.com or call us at (455)1234688.",
    "help":"I am here to help you.Please ask me anything",
    "default": "I am sorry,I didn't understand that.Can you please provide me some more details?"
}

def get_response(message):
    message=message.lower()

    for key in responses:
        if re.search(r'\b' + re.escape(key) + r'\b',message):
            return responses[key]
        
    return responses["default"]
    
def chatbot():

    print("Welcome to our customer service chatbot! Ask me anything about the organization.Type 'exit' to end the chat ")

    while True:
        user_input= input("You: ")
        if user_input.lower()== 'exit':
          print("ChatBot: Goodbye! Have a great day!")
          break
        response=get_response(user_input)
        print(f"Chatbot:{response}")
if __name__== "__main__":
        chatbot()  
    
ii)


def chatbot():
    print("Hello! I'm your chatbot. Type 'bye' to exit.")
    while True:
        user_input = input("You: ").lower()
        
        # Responses based on user input
        if "hello" in user_input:
            print("Chatbot: Hi there! How can I help you?")
        elif "how are you" in user_input:
            print("Chatbot: I'm just a program, but thanks for asking!")
        elif "what is your name" in user_input:
            print("Chatbot: I'm Chatbot 1.0!")
        elif "bye" in user_input:
            print("Chatbot: Goodbye! Have a great day!")
            break
        else:
            print("Chatbot: Sorry, I don't understand that.")

# Run the chatbot
chatbot()
